# Force the background to be black to fix the Warp "green screen" bug
set -g window-style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=colour234'

# set the pane border colors 
set -g focus-events on

# Ensure 256 color support is enabled
set -g default-terminal "xterm-256color"

setw -g mode-keys vi

set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'christoomey/vim-tmux-navigator'


set -g @resurrect-strategy-nvim 'session'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'